changelog:
  exclude:
    labels:
      - dependencies
      - github_actions
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug fixes 🛠
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
