site:
  url: http://localhost:8080
  title: Bonita Documentation Theme Preview
  start_page: showroom::index.adoc
  # Can be changed by setting the BONITA_THEME_URL environment variable when building
  # Remarks about the urls
  # For url related to AsciiDoc pages, they must be in the form of /bonita/dev/<page>.html for consistency and to make the
  # navigation opened to the right page. See gulp.d/tasks/build-preview-pages.js for the customization that makes it work.
  # homeUrl: &home_url /bonita/dev/index.html
runtime:
  log:
      # use pretty even on CI
      format: pretty
      # set to info to get details from the Antora extensions
      level: info
      # Antora exits with a non-zero exit code if a warning is logged -> https://docs.antora.org/antora/latest/playbook/runtime-log-failure-level
      failure_level: warn
  fetch: false
content:
  sources:
    # - url: './'
    #   branches: [HEAD]
    #   start_paths: 'showroom'

    - url: ./
      branches:
        - HEAD
      start_paths:
        - showroom


asciidoc:
  attributes:
    icons: font
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'

antora:
  extensions:
    - require: '@springio/antora-extensions/asciinema-extension'

ui:
  bundle:
    # url: https://github.com/bonitasoft/bonita-documentation-theme/releases/download/v1.23.0/bonita-documentation-theme-v1.23.0.zip
    url: ./build/ui-bundle.zip


