= Link between components

You can adding link between two components or between versions of the same component. To do it, you **must** use the `xref` syntax.

WARNING: **DO NOT** hard code urls with https://documentation.bonitasoft.com/xxxx or ../../my-page.adoc, use xref instead. An automatic check rejects your Pull Request if you hard code such links.

Rationale

* https://opendevise.com/blog/referencing-pages/
* such hard coded links only target the production environments, links won't work in preview environments
* not portable, such links cannot work if we want to generate the documentation in PDF format

The general form of a xref is `xref:<version>@<component_name>:<module>:<page>#anchor` and some elements are optional (version, module and anchor).

For more details about the xref syntax, see the Antora documentation to have a better understanding about version, component, module and anchor keyword:

* https://docs.antora.org/antora/3.0/page/xref/
* https://docs.antora.org/antora/3.0/page/page-links/

**Some example for you:**

|===
| Code Synthax | Comments

|`xref:ROOT:resource-management.adoc`
| a page in same component and same version

|`xref:bonita::about.adoc`
| a page in same version

|`xref:2022.2@bonita:ROOT:what-is-bonita.adoc`
| a page in same version

| `xref:2023.1@bonita::release-notes.adoc`
| a page of a given version in the ROOT module (implicit)

| `xref:2023.1@bonita:version-update:update-tool-overview.adoc#prerequisites`
| a page of a given version in the version-update module targeting an anchor

|===
