= Link between components
:page-editable: true

You can adding link between two components or between versions of the same component. To do it, you **must** use the `xref` syntax.

The general form of a xref is `xref:<version>@<component_name>:<module>:<page>#anchor` and some elements are optional (version, module and anchor).

**Some example for you:**

|===
| Code Synthax | Comments

|`xref:ROOT:resource-management.adoc`
| a page in same component and same version

|`xref:bonita::about.adoc`
| a page in same version

|`xref:2022.2@bonita:ROOT:what-is-bonita.adoc`
| a page in same version

| `xref:2023.1@bonita::release-notes.adoc`
| a page of a given version in the ROOT module (implicit)

| `xref:2023.1@bonita:version-update:update-tool-overview.adoc#prerequisites`
| a page of a given version in the version-update module targeting an anchor

|===

You can find more details in https://github.com/bonitasoft/bonita-documentation-site/blob/master/docs/content/CONTRIBUTING.adoc#adding-link-between-two-components-or-between-versions-of-the-same-component[our contributing documentation guide].
