== Test raw admonitions

[NOTE]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[TIP]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[IMPORTANT]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[WARNING]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[CAUTION]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====


== Test admonition in list

. blabla
+
[IMPORTANT]
====
Vive le paté
====
+
. blabla

---

* blabla
** Sous blabla
+
[WARNING]
====
Allez Grenoble
====
+
** Sous blabla
* blabla


== Test admonition with table content

[TIP]
====
|===
| Nom | Couleur de cheveux

| Titeuf
| Blond

| Mr propre
| _Chauve :'(_
|===
====


. blabla
. blabla
+
[CAUTION]
====
|===
| Nourriture | Comestible

| Saucisson
| Oui

| Brocolis
| Non
|===
====
+
. blabla


== Test title level

lalala

=== level 3

lalalalala

==== level 4

lalalalalalalala
-> no more levels

