== Test admonitions

[NOTE]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[TIP]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[IMPORTANT]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[WARNING]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[CAUTION]
====
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
====

[source,groovy]
----
List<List<String>> table = new ArrayList<List<String>>();
Set<Entry<String,String>> weatherDataEntries = weatherData.entrySet();
for (Entry<String,String> entry : weatherDataEntries) {
    List<String> row = new ArrayList<String>();
    row.add(entry.getKey());
    row.add(entry.getValue());
    table.add(row);
}
return table;
----
