= How to write a clean troubleshooting section


[.troubleshooting-title]
== Troubleshooting

[.troubleshooting-section]
--
[.symptom]
I can't wake up in the morning, 9AM is too early for me!!!

[.symptom-description]
When my alarm goes off, I turn it off and go right back to sleep.

[.cause]#Potential cause#
This is probably because I often go to bed at 3AM :'(

[.solution]#Possible solution#
I should just stop watching netflix for hours...
--

.Click to see *code example*
[%collapsible]
====
[source,text]
----
[.troubleshooting-section]
--
[.symptom]
I can't wake up in the morning, 9AM is too early for me!!!

[.symptom-description]
When my alarm goes off, I turn it off and go right back to sleep.

[.cause]#Potential cause#
This is probably because I often go to bed at 3AM :'(

[.solution]#Possible solution#
I should just stop watching netflix for hours...
--
----

====
[.troubleshooting-section]
--
[.symptom]
My code block is not display on troubleshooting solution section

[.symptom-description]
When i write some block code example, the display is not correct

[.cause]#Cause#
This is potentially because i miss an ending character after code block.

[.solution]#Possible solution#
[source,java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user(BonitaTestToolkit toolkit) {
        User user = toolkit.getUser("walter.bates");
        ...
    }
}
----
--

.Click to see *code example*
[%collapsible]
====
[source,text]
----
[.troubleshooting-section]
--
[.symptom]
I don't want display potential cause as title

[.symptom-description]
When i sure about the cause, I want to remove potential on title

[.cause]#Potential cause#
This is probably because I often go to bed at 3AM :'(

[.solution]#Possible solution#
Just write `Cause` as title
--
----
====

[.troubleshooting-section]
--
[.symptom]
I don't want display potential cause as title

[.symptom-description]
When i sure about the cause, I want to remove potential on title

[.cause]#Cause#
No doubt about the cause

[.solution]#Possible solution#
Just write `Cause` as title
--

.Click to see *code example*
[%collapsible]
====
[source,text]
----
[.troubleshooting-section]
--
[.symptom]
I don't want display potential cause as title

[.symptom-description]
When i sure about the cause, I want to remove potential on title

[.cause]#Cause#
This is probably because I often go to bed at 3AM :'(

[.solution]#Possible solution#
Just write `Cause` as title
--
----
====

[.troubleshooting-section]
--
[.symptom]
HTTP/1.1 401 Unauthorized

[.cause]#Cause#
The logged user has no permission to access the resources.

[.solution]#Possible solution#

1. Make sure that the cookies transferred are the ones generated during the last sucessfull login call

2. If one of the PUT, DELETE or POST method is used, make sure that the X-Bonita-API-Token header is included

3. If the X-Bonita-API-Token header is included, make sure that the value is the same as the one of the cookie generated during the last login

4. Maybe a logout was issued or the session has expired; try to log in again, and re-run the request with the new cookies and the new value for the X-Bonita-API-Token header.
--

.Click to see *code example*
[%collapsible]
====
[source,text]
----
[.troubleshooting-section]
--
[.symptom]
HTTP/1.1 401 Unauthorized

[.cause]#Cause#
The logged user has no permission to access the resources.

[.solution]#Possible solution#

1. Make sure that the cookies transferred are the ones generated during the last sucessfull login call

2. If one of the PUT, DELETE or POST method is used, make sure that the X-Bonita-API-Token header is included

3. If the X-Bonita-API-Token header is included, make sure that the value is the same as the one of the cookie generated during the last login

4. Maybe a logout was issued or the session has expired; try to log in again, and re-run the request with the new cookies and the new value for the X-Bonita-API-Token header.
--
----
====


== For theme tests only

Here we check the rendering depending on the title level.

[.troubleshooting-title]
== Troubleshooting 2

=== Troubleshooting 2 Without icon

[.troubleshooting-title]
=== Troubleshooting 3
=== Troubleshooting 3 Without icon

[.troubleshooting-title]
==== Troubleshooting 4

[.troubleshooting-section]
--
[.symptom]
I can't wake up in the morning, 9AM is too early for me!!!

[.symptom-description]
Here enter a symptom description

[.cause]#Potential cause#
This is probably because I often go to bed at 3AM :'(

[.solution]#Possible solution#
I should just stop watching netflix for hours...

[source,java]
----
@BonitaTests
class ProcessIT {

    @Test
    void should_retrieve_user(BonitaTestToolkit toolkit) {
        User user = toolkit.getUser("walter.bates");
        ...
    }
}
----
--
