= Cards
:page-editable: true

You can use card style in your page. Please don't abuse it, and try to only use it on index pages.

.Card display in after HTML generation
You can update *link*, *title* and description for each card.

WARNING: If description in card body is too long (more than 3 lines), we will hide the excess.

To do it, you need to use this following syntax:

[.card-section]
== Explore Bonita

Click on the *links* below to find useful information quickly, or use the *table of contents* to go straight to the information you want to read.


[.card.card-index]
--
http://www.bonitasoft.com/how-we-do-it/downloads[[.card-title]#Getting started tutorial# [.card-body.card-content-overflow]#pass:q[A JavaScript library of common assertions for testing smart contracts.]#]
--

[.card.card-index]
--
http://www.bonitasoft.com/how-we-do-it/downloads[[.card-title]#Bonita Studio installation# [.card-body.card-content-overflow]#pass:q[The very first step to start your Bonita project]#]
--

.Click to see the *source code*
[%collapsible]
====
[source,asciidoc]
----
[.card-section]
== Explore Bonita

Click on the *links* below to find useful information quickly, or use the *table of contents* to go straight to the information you want to read.


[.card.card-index]
--
http://www.bonitasoft.com/how-we-do-it/downloads[[.card-title]#Getting started tutorial# [.card-body.card-content-overflow]#pass:q[A JavaScript library of common assertions for testing smart contracts.]#]
--

[.card.card-index]
--
http://www.bonitasoft.com/how-we-do-it/downloads[[.card-title]#Bonita Studio installation# [.card-body.card-content-overflow]#pass:q[The very first step to start your Bonita project]#]
--
----
====

