name: 'Build Setup'
description: 'Setup node'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      shell: bash
      run: npm ci
