name: Build PR preview

on:
  pull_request:
    branches:
      - master
      # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
#    paths:
#      - 'modules/ROOT/**'
#      - 'antora.yml'
#      - '.github/workflows/build-pr-preview.yml'
jobs:
  build_preview:
    runs-on: ubuntu-20.04
    env:
#      COMPONENT_NAME: preview
#      # Except if you want to test in progress work that your content depends on, keep it set to master
#      DOC_SITE_BRANCH: master
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v2
      - name: Publish preview
        id: preview_step
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_DOC }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          failOnError: true
          teardown: 'true'
          build: |
            npm install
            gulp preview:build
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
