name: Commit Message format check 

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-20.04
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
