name: Create release

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Bundle documentation theme
        run: npm run bundle
      - name: Change bundle name
        run: mv build/ui-bundle.zip build/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.JC_TOKEN }}
          repository: jeromecambon/bonita-documentation-site
          event-type: new_theme_bundle
          client-payload: '{"release": "${{ env.RELEASE_VERSION }}", "file": "bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip", "url": "https://github.com/jeromecambon/bonita-documentation-theme/releases/download/${{ env.RELEASE_VERSION }}/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip"}'
